import datetime
from sqlalchemy.orm import Session
from backend.database.models import User, UserProfile, ReferralCode, TeamMember, Team, LeaderApplication, MemberApplication
from backend.modules.auth.repository import UserRepository
from backend.utils.security import (
    get_password_hash,
    verify_password,
    create_access_token,
    create_refresh_token
)

class AuthService:
    """
    AuthService coordinates all authentication workflows including password hashing,
    JWT token generation, brute-force locking, and closed-loop referral signups.
    """
    def __init__(self, db: Session):
        self.db = db
        self.user_repo = UserRepository(db)

    def login(self, username_or_phone: str, plain_password: str) -> dict:
        """
        Validates credentials and generates JWT credentials.
        Tracks failed logins and enforces 30-minute locks after 5 consecutive errors.
        """
        # 1. Fetch user by username or phone number
        user = self.user_repo.get_by_username(username_or_phone)
        if not user:
            user = self.user_repo.get_by_phone_number(username_or_phone)
            
        if not user:
            raise ValueError("INVALID_CREDENTIALS")

        # 2. Check brute force locked constraints
        utcnow = datetime.datetime.utcnow()
        if user.locked_until and user.locked_until > utcnow:
            minutes_left = int((user.locked_until - utcnow).total_seconds() / 60) + 1
            raise ValueError(f"ACCOUNT_LOCKED_{minutes_left}_MINUTES")

        # 3. Verify password hash
        if not verify_password(plain_password, user.password_hash):
            # Increment failed attempts
            user.failed_login_attempts += 1
            if user.failed_login_attempts >= 5:
                user.locked_until = utcnow + datetime.timedelta(minutes=30)
                self.db.commit()
                raise ValueError("ACCOUNT_LOCKED_30_MINUTES")
            self.db.commit()
            raise ValueError("INVALID_CREDENTIALS")

        # 4. Success -> Reset failed attempts and update last_login
        user.failed_login_attempts = 0
        user.locked_until = None
        user.last_login = utcnow
        self.db.commit()

        # 5. Generate tokens
        access_token = create_access_token(str(user.id), user.role, user.must_change_password)
        refresh_token = create_refresh_token(str(user.id))

        return {
            "access_token": access_token,
            "refresh_token": refresh_token,
            "token_type": "bearer",
            "must_change_password": user.must_change_password
        }

    def signup(self, username: str, phone_number: str, plain_password: str, referral_code_str: str) -> User:
        """
        Handles citizen onboarding. Enforces strict closed-loop invite checks:
        - Admin-issued LEADER codes register vetted leaders.
        - Leader-issued TEAM codes register standard members.
        All entities are created within a single atomic database transaction.
        """
        # 1. Enforce uniqueness constraints
        if self.user_repo.get_by_username(username):
            raise ValueError("USERNAME_TAKEN")
        if self.user_repo.get_by_phone_number(phone_number):
            raise ValueError("PHONE_REGISTERED")

        # 2. Validate referral invitation code
        ref_code = self.db.query(ReferralCode).filter(
            ReferralCode.code == referral_code_str,
            ReferralCode.is_active == True
        ).first()

        if not ref_code:
            raise ValueError("INVALID_REFERRAL_CODE")

        # Enforce expiration dates
        if ref_code.expires_at < datetime.datetime.utcnow():
            ref_code.is_active = False
            self.db.commit()
            raise ValueError("REFERRAL_CODE_EXPIRED")

        # Enforce usage bounds
        if ref_code.used_count >= ref_code.max_usage:
            ref_code.is_active = False
            self.db.commit()
            raise ValueError("REFERRAL_CODE_EXPIRED")

        # 3. Determine signup role mapping
        signup_role = "MEMBER"
        if ref_code.referral_type == "LEADER":
            signup_role = "LEADER"

        # 4. Execute atomic signup inside transaction
        try:
            # Create user entity
            hashed_pwd = get_password_hash(plain_password)
            user = User(
                username=username,
                phone_number=phone_number,
                password_hash=hashed_pwd,
                role=signup_role,
                user_status="ACTIVE",  # Active upon successful referral onboard
                is_verified=False
            )
            self.db.add(user)
            self.db.flush()  # Extract user UUIDv7 natively generated by default

            # Determine if there's an approved application to pre-fill data
            prefill_name = username
            prefill_email = None
            prefill_masked_aadhaar = None
            prefill_aadhaar_hash = None
            
            if signup_role == "LEADER":
                app = self.db.query(LeaderApplication).filter(
                    LeaderApplication.phone == phone_number,
                    LeaderApplication.status == "APPROVED"
                ).first()
                if app:
                    prefill_name = app.full_name
                    prefill_email = app.email
                    prefill_masked_aadhaar = app.masked_aadhaar
                    prefill_aadhaar_hash = app.aadhaar_hash
            elif signup_role == "MEMBER":
                app = self.db.query(MemberApplication).filter(
                    MemberApplication.phone == phone_number,
                    MemberApplication.status == "APPROVED"
                ).first()
                if app:
                    prefill_name = app.full_name
                    prefill_email = app.email
                    prefill_masked_aadhaar = app.masked_aadhaar
                    prefill_aadhaar_hash = app.aadhaar_hash

            # Create profile container
            profile = UserProfile(
                user_id=user.id,
                full_name=prefill_name,
                email=prefill_email,
                masked_aadhaar=prefill_masked_aadhaar,
                aadhaar_hash=prefill_aadhaar_hash,
                profile_completion=0
            )
            self.db.add(profile)

            # If Member (referral type TEAM), create active membership linkage
            if signup_role == "MEMBER" and ref_code.team_id:
                # Confirm target team exists and is active
                target_team = self.db.query(Team).filter(
                    Team.id == ref_code.team_id,
                    Team.status == "ACTIVE"
                ).first()
                if not target_team:
                    raise ValueError("TEAM_INACTIVE")

                member = TeamMember(
                    team_id=ref_code.team_id,
                    member_id=user.id,
                    joined_level=target_team.current_level
                )
                self.db.add(member)

            # Update used count -> Triggers will automatically handle deactivations
            ref_code.used_count += 1
            
            self.db.commit()
            return user
        except Exception as e:
            self.db.rollback()
            raise ValueError(f"SIGNUP_FAILED: {str(e)}")

    def change_password(self, user_id: str, current_password: str, new_password: str, new_username: str = None):
        """Forces password change and resets must_change_password flag, optionally updating the username."""
        import uuid
        if isinstance(user_id, str):
            user_id = uuid.UUID(user_id)
        user = self.db.query(User).filter(User.id == user_id).first()
        if not user:
            raise ValueError("USER_NOT_FOUND")
            
        if not verify_password(current_password, user.password_hash):
            raise ValueError("INVALID_CURRENT_PASSWORD")
            
        # Optional: change username
        if new_username and new_username.strip() and new_username.strip() != user.username:
            new_username = new_username.strip()
            # check uniqueness
            existing = self.user_repo.get_by_username(new_username)
            if existing:
                raise ValueError("USERNAME_TAKEN")
            user.username = new_username

        user.password_hash = get_password_hash(new_password)
        user.must_change_password = False
        user.password_changed_at = datetime.datetime.utcnow()
        self.db.commit()
