from typing import Optional, List
from sqlalchemy.orm import Session
from uuid import UUID
import datetime

from backend.repositories.base import BaseRepository
from backend.database.models import ReferralCode

class ReferralRepository(BaseRepository[ReferralCode]):
    """ReferralRepository implements database queries for referral invitation codes."""
    def __init__(self, db: Session):
        super().__init__(ReferralCode, db)

    def get_by_code(self, code: str) -> Optional[ReferralCode]:
        """Fetch referral record matching the unique alphanumeric code."""
        return self.db.query(self.model).filter(self.model.code == code).first()

    def get_active_team_referral(self, team_id: UUID) -> Optional[ReferralCode]:
        """
        Fetch the current active, unexpired member invitation code for the team.
        Checks usage and expiration bounds.
        """
        utcnow = datetime.datetime.utcnow()
        return self.db.query(self.model).filter(
            self.model.team_id == team_id,
            self.model.referral_type == "TEAM",
            self.model.is_active == True,
            self.model.used_count < self.model.max_usage,
            self.model.expires_at > utcnow
        ).first()

    def get_all_by_generator(self, generator_id: UUID) -> List[ReferralCode]:
        """Fetch all referral codes generated by a specific user account (Admin or Leader)."""
        return self.db.query(self.model).filter(self.model.generated_by == generator_id).all()
